### ISSUE TITLE
Infinite loop in ICODecoder

### ISSUE THREAD

**Issue by achernoprudov** [imcdonagh/image4j#1]
Hello. I have found an infinite loop if i try to decode ICO image from ByteArrayInputStream. When I put file in FileInputStream it is ok.

```
final File file = new File("/tmp/logo.ico");
final FileInputStream is = new FileInputStream(file);
List<BufferedImage> imageContainer = ICODecoder.read(is);
```

But when I try to decode image from ByteArrayInputStream in stucks in loop at  net.sf.image4j.codec.ico.ICODecoder.readExt(ICODecoder.java:155).

```
final File file = new File("/tmp/logo.ico");
final FileInputStream fileInputStream = new FileInputStream(file);
final byte[] byteArray = IOUtils.toByteArray(fileInputStream);
final ByteArrayInputStream is = new ByteArrayInputStream(byteArray);
List<BufferedImage> imageContainer = ICODecoder.read(is);
```

Here is ICO file:
https://mega.nz/#!ZwYzBKYC!O6Y4_jQH7SyYin2e5UYB-GIwxU2IShb0ylkOjUdUbIQ

**Comment by Ph3n1x** [comment]
I had the same problem but discovered, that I was using the version 0.7 from the maven repo. In version 0.7.1 the infinite loop is fixed. Sadly, that version is not uploaded to the maven repo...
