### ISSUE TITLE
Release a version that includes the better error handling from Feb 2015

### ISSUE THREAD

**Issue by william-ferguson-au** [imcdonagh/image4j#2]
Any plans to cut another release?

**Comment by imcdonagh** [comment]
Hi @william-ferguson-au, can you elaborate on the 'better error handling' you mentioned in the title of this issue?

**Comment by william-ferguson-au** [comment]
I can't recall the details now. My recollection is that one of the commits made in Feb 2016 provides much better information about the cause of failure when it fails to open an Icon because the Icon had been created with/without compression.

**Comment by imcdonagh** [comment]
If you had a sample problem icon file to test with, I could take a look and see how the error handling could be improved. Let me know if that works for you.

**Comment by william-ferguson-au** [comment]
Sorry I don't.

MY recollection is that the error handling in master is just fine now. Just not in the most recent release. I needed to build from HEAD in order to determine the problem with the icon.

That's why I was asking about plans to cut a release.

**Comment by imcdonagh** [comment]
I know it's a while since this exchange, but for what it's worth, I just pushed release 0.7.2 to Sourceforge, which brings the releases up to date with the fixes in the Github repo.
