### ISSUE TITLE
Debugging code in the trunk leaving images behind in tmpdir.

### ISSUE THREAD

**Issue by Farmbuyer** [imcdonagh/image4j#3]
Normally I would never submit a bug report for debugging code in the trunk, but as the codebase hasn't changed for a year, I want to put this out there as a reminder.

In `codec/ico/ICODecoder.java` around lines 200 and 330 are two tiny (essentially identical) blocks of code which write out the current image data to a temporary file, as an aid to debugging.  The first block of code is commented out.  The second block, however, is not.  Be aware that if you drop the current source into your project as-is that image files will begin appearing in `java.io.tmpdir`.  They are not automatically deleted at program exit (obviously, because that would defeat the purpose of writing them in the first place).

My advice to new users is to comment out the tmpfile code at about line 330 or so.

**Comment by imcdonagh** [comment]
Thanks @Farmbuyer, the debug code has been removed.
